runtime: nodejs20

instance_class: F1

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 30ms

env_variables:
  NODE_ENV: production

handlers:
  - url: /.*
    script: auto
    secure: always

secret_environment_variables:
  - name: SLACK_WEBHOOK_URL
    secret: GOCOMET_SLACK_WEBHOOK
    version: latest
